* pom.xml - fixed the issue that 'mvn clean install' doesn't even work - build now creates war file instead of jar - upgrade jetty version to latest and comment out a lot of junk
* Moved /src/test/webapp to /src/main

* web.xml: changed servlet api from 2.5 to 3.0, else running jetty:run will have error
  java.lang.IllegalStateException: Multiple servlets map to path: /zkau/* ...